option:
  style: european   #european | american
  type: put
  s_max: 300.0

dir:
  data: data/processed/
save_mc: true

seed: 42
n_paths: 50000
n_steps: 252

s0: 100.0
k: 100.0
t: 0.25
r: 0.02
sigma: 0.1


